version: '3.8'

services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes:
    - ./metabase:/dev/random:ro
    ports:
      - 3000:3000
    restart: always 
  db:
    image: mysql
    container_name: mysql
    restart: always
    cap_add:
      - SYS_NICE 
    environment:
      - MYSQL_ROOT_PASSWORD=mama
      - MYSQL_DATABASE=mydb
    ports:
      - '8888:3306'
    volumes:
      - ./db:/home/app
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
